clc;
clear;
disp('Detailed Student Counts (Venn Region Counts)');
Total = 100;
M = 45; P = 50; C = 40;
M_P = 20; M_C = 15; P_C = 10;
M_P_C = 5;
Total_One_or_More = M + P + C - (M_P + M_C + P_C) + M_P_C;
None_Study = Total - Total_One_or_More;
M_P_C_count = 5;
Exactly_M_P = M_P - M_P_C_count;
Exactly_M_C = M_C - M_P_C_count;
Exactly_P_C = P_C - M_P_C_count;
Only_Two = Exactly_M_P + Exactly_M_C + Exactly_P_C;
Only_M = M - M_P - M_C + M_P_C_count;
Only_P = P - M_P - P_C + M_P_C_count;
Only_C = C - M_C - P_C + M_P_C_count;
Only_One = Only_M + Only_P + Only_C;
None_Study_count = None_Study;
fprintf('Students who like ALL three subjects: %d\n', M_P_C_count);
fprintf('Students who like EXACTLY two subjects: %d\n', Only_Two);
fprintf('Students who like EXACTLY one subject: %d\n', Only_One);
fprintf('Students who do NOT like any subjects: %d\n', None_Study_count);
