fprintf("Write a MATLAB code to imlpement Newton's Interpolation Formula\n");
fprintf("Output:\n1. difference table\n2. simplified equation\n" + ...
    "3. Graph of the interpolation eqn\n4. Calculated value\n" + ...
    "\nplot\nsubplot\ngrid\nxlabel\nylabel\nsyms");